### ISSUE TITLE
A CTRL+D make bshell infinite looping

### ISSUE THREAD

**Issue by Cadichon** [bihanviranga/bshell#15]
A CTRL+D should exit bshell, not make it infinite looping

**Comment by bihanviranga** [comment]
I thought the EOF check in `bshell_read_line()` would solve this. Will look into this further.

**Comment by buffet** [comment]
The issue here is essentially that you tread EOF the same as return.

Multiple approaches to this:
- return NULL
- return some kind of struct
- have an out param that indicates that you want to exit

**Comment by bihanviranga** [comment]
Apparently getchar() returns -1 when ctrl+d is given as input. I'm going to add a check for -1 return value and exit. Hope I'm going about this correctly.
